/**
 * TweenForge — Clip Studio Paint Plugin
 *
 * This script runs inside CSP's scripting environment (Clip Studio Paint v2.x+).
 * It exports selected key frames, calls the TweenForge server, and imports
 * the generated inbetween frames back into the animation timeline.
 *
 * Installation:
 *   1. Start the TweenForge server:  tweenforge serve
 *   2. In CSP: File > Script > Run Script... > select this file
 *
 * Configuration:
 *   The script reads connection settings from ~/.tweenforge/csp_config.json
 *   (generated by `tweenforge serve`). If the file doesn't exist, it falls
 *   back to http://127.0.0.1:9817.
 */

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

var CONFIG = {
    serverUrl: "http://127.0.0.1:9817",
    tempDir: "",  // will be set from config or OS temp
};

function loadConfig() {
    // Try to read the config file generated by the TweenForge server
    var home = (typeof process !== "undefined" && process.env && process.env.HOME)
        ? process.env.HOME
        : "~";
    var configPath = home + "/.tweenforge/csp_config.json";

    try {
        var file = new File(configPath);
        if (file.exists) {
            file.open("r");
            var content = file.read();
            file.close();
            var cfg = JSON.parse(content);
            CONFIG.serverUrl = cfg.server_url || CONFIG.serverUrl;
            CONFIG.tempDir = cfg.temp_dir || CONFIG.tempDir;
        }
    } catch (e) {
        // Config file not found — use defaults
    }

    if (!CONFIG.tempDir) {
        CONFIG.tempDir = home + "/.tweenforge/tmp";
    }
}

// ---------------------------------------------------------------------------
// Server communication
// ---------------------------------------------------------------------------

/**
 * Call the TweenForge server's native interpolation endpoint.
 * Requires frames to be saved to disk first.
 */
function callInterpolate(frameAPath, frameBPath, numInbetweens, easing, lineartMode, outputDir) {
    var url = CONFIG.serverUrl + "/interpolate";
    var body = JSON.stringify({
        frame_a_path: frameAPath,
        frame_b_path: frameBPath,
        num_inbetweens: numInbetweens,
        easing: easing,
        lineart_mode: lineartMode,
        output_dir: outputDir,
    });

    var xhr = new XMLHttpRequest();
    xhr.open("POST", url, false);  // synchronous
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.send(body);

    if (xhr.status === 200) {
        return JSON.parse(xhr.responseText);
    } else {
        throw new Error("TweenForge server returned status " + xhr.status + ": " + xhr.responseText);
    }
}

/**
 * Check if the server is reachable.
 */
function checkHealth() {
    try {
        var xhr = new XMLHttpRequest();
        xhr.open("GET", CONFIG.serverUrl + "/health", false);
        xhr.send();
        return xhr.status === 200;
    } catch (e) {
        return false;
    }
}

// ---------------------------------------------------------------------------
// CSP document interaction
// ---------------------------------------------------------------------------

/**
 * Export the current animation cel as a PNG file.
 * Returns the path to the exported file.
 */
function exportCurrentFrame(frameNumber, outputDir) {
    var doc = app.activeDocument;
    var filename = "keyframe_" + String(frameNumber).padStart(4, "0") + ".png";
    var filepath = outputDir + "/" + filename;

    // Navigate to the target frame
    doc.animation.currentFrame = frameNumber;

    // Use CSP's built-in export — this is the most reliable method
    // For CSP v2.x scripting, we use the rasterize-and-save approach
    try {
        app.executeMenuCommand("file_export_png");
        // Note: CSP's executeMenuCommand may open a dialog. In automated mode,
        // we'd need to use the non-interactive export API if available.
        // Fallback: save the entire canvas via doc.exportImage()
    } catch (e) {
        // If menu command fails, try programmatic export
    }

    return filepath;
}

/**
 * Import a PNG file as a new animation cel at the specified frame.
 */
function importFrameAsCel(imagePath, targetFrame) {
    var doc = app.activeDocument;

    doc.animation.currentFrame = targetFrame;

    // Import the image as a new layer, then assign it to the current cel
    try {
        app.executeMenuCommand("file_import_image");
        // This would need to be pointed at imagePath — CSP scripting
        // may require user interaction here. See DESIGN.md for alternatives.
    } catch (e) {
        // Fallback: copy the file to CSP's import watch folder
    }
}

// ---------------------------------------------------------------------------
// Main workflow
// ---------------------------------------------------------------------------

function main() {
    loadConfig();

    // 1. Check server connectivity
    if (!checkHealth()) {
        alert(
            "TweenForge server is not running.\n\n" +
            "Start it with: tweenforge serve\n" +
            "Then run this script again."
        );
        return;
    }

    // 2. Prompt user for parameters
    var frameA = parseInt(prompt("Start key frame number:", "1"), 10);
    var frameB = parseInt(prompt("End key frame number:", "5"), 10);
    var numInbetweens = parseInt(prompt("Number of inbetweens:", "3"), 10);
    var easing = prompt("Easing (linear / ease_in / ease_out / ease_in_out):", "linear");
    var lineartMode = confirm("Apply line art cleanup?");

    if (isNaN(frameA) || isNaN(frameB) || isNaN(numInbetweens)) {
        alert("Invalid input. Please enter valid frame numbers.");
        return;
    }

    if (frameB <= frameA) {
        alert("End frame must be after start frame.");
        return;
    }

    // 3. Ensure temp directories exist
    var outputDir = CONFIG.tempDir + "/output_" + Date.now();
    var exportDir = CONFIG.tempDir + "/export_" + Date.now();

    // 4. Export key frames
    var pathA = exportCurrentFrame(frameA, exportDir);
    var pathB = exportCurrentFrame(frameB, exportDir);

    // 5. Call the server
    var result;
    try {
        result = callInterpolate(pathA, pathB, numInbetweens, easing, lineartMode, outputDir);
    } catch (e) {
        alert("Interpolation failed: " + e.message);
        return;
    }

    if (result.status !== "complete") {
        alert("Interpolation error: " + (result.error || "unknown"));
        return;
    }

    // 6. Import generated frames
    var generatedFrames = result.frames;
    for (var i = 0; i < generatedFrames.length; i++) {
        var targetFrame = frameA + i + 1;
        importFrameAsCel(generatedFrames[i], targetFrame);
    }

    alert("TweenForge: Generated " + generatedFrames.length + " inbetween frame(s).");
}

// Run
main();
